POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Videonode",
  "description": "Esse é o vídeo 01",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/fb9100eb-87f7-4a43-8d11-ec1aefc9e262
Content-Type: application/json

{
  "title": "Videonode",
  "description": "Esse é o vídeo node",
  "duration" : 400
}

###

DELETE http://localhost:3333/videos/a44894e4-7897-42a0-a932-48177eda7a65