POST https://node-do-zero-q96t.onrender.com/videos
Content-Type: application/json

{
  "title": "Videonode",
  "description": "Esse é o vídeo 01",
  "duration": 180
}

###

GET https://node-do-zero-q96t.onrender.com/videos

###

PUT https://node-do-zero-q96t.onrender.com/videos/fb9100eb-87f7-4a43-8d11-ec1aefc9e262
Content-Type: application/json

{
  "title": "Video01",
  "description": "Esse é o vídeo de n° 01",
  "duration" : 400
}

###

DELETE https://node-do-zero-q96t.onrender.com/videos/fb9100eb-87f7-4a43-8d11-ec1aefc9e262